import { medusaIntegrationTestRunner } from "@medusajs/test-utils"
import { Modules } from "@medusajs/framework/utils"
import seed from "../../src/scripts/seed"
jest.setTimeout(120000)
// Native Medusa + PostgreSQL contract tests. The browser fixture is deliberately not used here.
medusaIntegrationTestRunner({testSuite:({api,getContainer})=>{
 let headers:Record<string,string>,owner:Record<string,string>,other:Record<string,string>,customerId:string,regionId:string,productId:string
 async function account(email:string){const register=await api.post("/auth/customer/emailpass/register",{email,password:"A native contract password!"});const created=await api.post("/store/customers",{email,first_name:"Anaya",last_name:"Shah"},{headers:{...headers,Authorization:`Bearer ${register.data.token}`}});const login=await api.post("/auth/customer/emailpass",{email,password:"A native contract password!"});return {id:created.data.customer.id,headers:{...headers,Authorization:`Bearer ${login.data.token}`}}}
 beforeAll(async()=>{const container=getContainer();await seed({container,args:[]});const [key]=await container.resolve(Modules.API_KEY).listApiKeys({title:"MINARA Storefront"});headers={"x-publishable-api-key":key.token};const regions=await api.get("/store/regions",{headers});regionId=regions.data.regions[0].id;const products=await api.get("/store/products?handle=classic-mango-pickle",{headers});productId=products.data.products[0].id;const first=await account("owner@example.test");customerId=first.id;owner=first.headers;other=(await account("other@example.test")).headers;})
 it("persists wishlist entries idempotently and scopes them to the signed-in customer",async()=>{for(let i=0;i<2;i++)await api.post("/store/minara/wishlist",{product_id:productId,saved:true},{headers:owner});expect((await api.get("/store/minara/wishlist",{headers:owner})).data.products).toHaveLength(1);expect((await api.get("/store/minara/wishlist",{headers:other})).data.products).toHaveLength(0);await api.post("/store/minara/wishlist",{product_id:productId,saved:false},{headers:owner});expect((await api.get("/store/minara/wishlist",{headers:owner})).data.products).toHaveLength(0)})
 it("protects assigned cart reads, edits and transfers from another account",async()=>{const created=await api.post("/store/carts",{region_id:regionId},{headers});const path=`/store/carts/${created.data.cart.id}`;await api.post(`${path}/customer`,{},{headers:owner});for(const h of [headers,other]){expect((await api.get(path,{headers:h,validateStatus:()=>true})).status).toBe(404);expect((await api.post(`${path}/customer`,{},{headers:h,validateStatus:()=>true})).status).toBeGreaterThanOrEqual(400)}expect((await api.get(path,{headers:owner})).status).toBe(200)})
 it("protects native order detail by customer ownership",async()=>{const order=await getContainer().resolve(Modules.ORDER).createOrders({region_id:regionId,currency_code:"inr",customer_id:customerId,email:"owner@example.test",items:[]});expect((await api.get(`/store/orders/${order.id}`,{headers:owner})).status).toBe(200);expect((await api.get(`/store/orders/${order.id}`,{headers:other,validateStatus:()=>true})).status).toBe(404);expect((await api.get(`/store/orders/${order.id}`,{headers,validateStatus:()=>true})).status).toBe(401)})
 it("prevents an address ID from another customer being updated",async()=>{const added=await api.post("/store/customers/me/addresses",{first_name:"Anaya",last_name:"Shah",address_1:"12 Garden Road",city:"Pune",province:"Maharashtra",country_code:"in",postal_code:"411001",phone:"9876543210"},{headers:owner});const id=added.data.customer.addresses[0].id;const result=await api.post(`/store/customers/me/addresses/${id}`,{city:"Elsewhere"},{headers:other,validateStatus:()=>true});expect(result.status).toBeGreaterThanOrEqual(400);expect((await api.get("/store/customers/me/addresses",{headers:owner})).data.addresses[0].city).toBe("Pune")})
 it("does not permit native manual payment initialization while checkout is closed",async()=>{const cart=await api.post("/store/carts",{region_id:regionId},{headers:owner});const response=await api.post("/store/payment-collections",{cart_id:cart.data.cart.id},{headers:owner,validateStatus:()=>true});expect(response.status).toBe(503)})
}})
