import { decorateCartTotals } from "@medusajs/framework/utils";
import { createHmac } from "node:crypto";
import CashfreeProvider, {
  toCashfreeAmount,
  validCashfreeWebhook,
} from "../service";

const options = {
  client_id: "client_fixture",
  client_secret: "server_secret",
  environment: "sandbox" as const,
  api_version: "2025-01-01",
  storefront_url: "https://store.example.test",
  backend_url: "https://api.example.test",
};
const sessionId = "payses_fixture";
const orderId = "mn_" + "a".repeat(32);
const data = {
  order_id: orderId,
  amount: 198,
  currency: "INR" as const,
  session_id: sessionId,
  payment_session_id: "session_cashfree_fixture",
  mode: "sandbox" as const,
};
const order = {
  order_id: orderId,
  order_amount: data.amount,
  order_currency: "INR",
  payment_session_id: data.payment_session_id,
  order_tags: { medusa_session_id: sessionId },
};
const payment = {
  cf_payment_id: "123456789",
  order_id: orderId,
  payment_amount: data.amount,
  payment_currency: "INR",
  payment_status: "SUCCESS",
};
let fetchMock: jest.SpyInstance;

function respond(value: unknown, status = 200) {
  return new Response(JSON.stringify(value), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

beforeEach(() => {
  fetchMock = jest.spyOn(globalThis, "fetch");
});
afterEach(() => jest.restoreAllMocks());

it("keeps Cashfree amounts in exact INR major units", () => {
  expect(toCashfreeAmount(198)).toBe(198);
  expect(toCashfreeAmount("10.25")).toBe(10.25);
  for (const value of [0, -1, Infinity, "abc", 0.001, Number.MAX_SAFE_INTEGER]) {
    expect(() => toCashfreeAmount(value)).toThrow();
  }
});

it("creates an idempotent Cashfree order with trusted customer details", async () => {
  fetchMock.mockResolvedValue(
    respond({
      ...order,
      order_id: expect.anything(),
    }),
  );
  // Return the deterministic order id generated by the provider.
  fetchMock.mockImplementationOnce(async (_url: string, init: RequestInit) => {
    const body = JSON.parse(String(init.body));
    return respond({
      order_id: body.order_id,
      order_amount: body.order_amount,
      order_currency: body.order_currency,
      payment_session_id: "session_cashfree_fixture",
      order_tags: body.order_tags,
    });
  });
  const result = await new CashfreeProvider({}, options).initiatePayment({
    amount: 198,
    currency_code: "inr",
    context: { idempotency_key: sessionId },
    data: {
      customer_id: "cus_fixture",
      customer_email: "buyer@example.test",
      customer_phone: "9876543210",
      customer_name: "Anaya Shah",
    },
  });
  const [, init] = fetchMock.mock.calls[0];
  const body = JSON.parse(String(init.body));
  expect(body.order_amount).toBe(198);
  expect(body.customer_details.customer_phone).toBe("9876543210");
  expect(body.order_tags.medusa_session_id).toBe(sessionId);
  expect(init.headers["x-idempotency-key"]).toMatch(/^[0-9a-f-]{36}$/);
  expect(JSON.stringify(result)).not.toContain(options.client_secret);
  expect(result.data.payment_session_id).toBe("session_cashfree_fixture");
});

it("does not authorize a browser claim without a successful Cashfree payment", async () => {
  fetchMock.mockImplementation(async (url: string) =>
    respond(url.endsWith("/payments") ? [] : order),
  );
  const result = await new CashfreeProvider({}, options).authorizePayment({
    data: { ...data, cf_payment_id: "forged" },
  });
  expect(result.status).toBe("requires_more");
});

it("authorizes only a matching Cashfree SUCCESS payment", async () => {
  fetchMock.mockImplementation(async (url: string) =>
    respond(url.endsWith("/payments") ? [payment] : order),
  );
  const result = await new CashfreeProvider({}, options).authorizePayment({ data });
  expect(result.status).toBe("captured");
  expect(result.data.cf_payment_id).toBe(String(payment.cf_payment_id));
});

it("rejects an order amount mismatch", async () => {
  fetchMock.mockImplementation(async (url: string) =>
    respond(url.endsWith("/payments") ? [payment] : { ...order, order_amount: 1 }),
  );
  await expect(
    new CashfreeProvider({}, options).authorizePayment({ data }),
  ).rejects.toThrow("mismatch");
});

it("never changes the amount after payment starts", async () => {
  await expect(
    new CashfreeProvider({}, options).updatePayment({
      data,
      amount: 199,
      currency_code: "inr",
    }),
  ).rejects.toThrow("cannot be changed");
  expect(fetchMock).not.toHaveBeenCalled();
});

it("treats Cashfree SUCCESS as already captured", async () => {
  fetchMock.mockImplementation(async (url: string) =>
    respond(url.endsWith("/payments") ? [payment] : order),
  );
  await new CashfreeProvider({}, options).capturePayment({ data });
  expect(fetchMock.mock.calls.every(([, init]) => !init?.body)).toBe(true);
});

it("validates Cashfree timestamp + raw-body base64 webhook signatures", () => {
  const raw = '{"type":"PAYMENT_SUCCESS_WEBHOOK"}';
  const timestamp = "1758276000000";
  const signature = createHmac("sha256", options.client_secret)
    .update(`${timestamp}${raw}`)
    .digest("base64");
  expect(
    validCashfreeWebhook(raw, timestamp, signature, options.client_secret),
  ).toBe(true);
  expect(
    validCashfreeWebhook(raw + " ", timestamp, signature, options.client_secret),
  ).toBe(false);
  expect(validCashfreeWebhook(raw, timestamp, "bad", options.client_secret)).toBe(
    false,
  );
});

it("derives webhook session state from Cashfree instead of browser data", async () => {
  fetchMock.mockResolvedValue(respond(order));
  const raw = JSON.stringify({
    type: "PAYMENT_SUCCESS_WEBHOOK",
    data: { order, payment },
  });
  const timestamp = "1758276000000";
  const result = await new CashfreeProvider({}, options).getWebhookActionAndData({
    rawData: Buffer.from(raw),
    data: { session_id: "foreign" },
    headers: {
      "x-webhook-timestamp": timestamp,
      "x-webhook-signature": createHmac("sha256", options.client_secret)
        .update(`${timestamp}${raw}`)
        .digest("base64"),
    },
  });
  expect(result.action).toBe("captured");
  expect(result.data?.session_id).toBe(sessionId);
  expect(Number(String(result.data?.amount))).toBe(198);
});

it("uses a stable Cashfree idempotency key for refund retries", async () => {
  fetchMock.mockImplementation(async (url: string, init?: RequestInit) => {
    if (url.endsWith("/refunds")) {
      const body = JSON.parse(String(init?.body));
      return respond({
        ...body,
        refund_currency: "INR",
        refund_status: "PENDING",
      });
    }
    return respond(url.endsWith("/payments") ? [payment] : order);
  });
  const provider = new CashfreeProvider({}, options);
  await provider.refundPayment({
    data,
    amount: 10,
    context: { idempotency_key: "ref_123" },
  });
  const refundCall = fetchMock.mock.calls.find(([url]) =>
    String(url).endsWith("/refunds"),
  );
  expect(refundCall?.[1].headers["x-idempotency-key"]).toMatch(/^[0-9a-f-]{36}$/);
});

it("cannot cancel a successful payment as though it were unpaid", async () => {
  fetchMock.mockImplementation(async (url: string) =>
    respond(url.endsWith("/payments") ? [payment] : order),
  );
  await expect(
    new CashfreeProvider({}, options).cancelPayment({ data }),
  ).rejects.toThrow("Refund");
});

it("uses native tax-exclusive summary components without counting delivery twice", () => {
  const totals = decorateCartTotals(
    {
      currency_code: "inr",
      items: [
        {
          id: "item",
          unit_price: 100,
          is_tax_inclusive: false,
          quantity: 1,
          tax_lines: [{ rate: 10 }],
          adjustments: [{ amount: 10, is_tax_inclusive: false }],
        },
      ],
      shipping_methods: [
        {
          id: "shipping",
          amount: 20,
          is_tax_inclusive: false,
          tax_lines: [{ rate: 10 }],
        },
      ],
    },
    { includeTaxes: true },
  );
  expect(Number(String(totals.subtotal))).toBe(120);
  expect(Number(String(totals.shipping_total))).toBe(22);
  expect(Number(String(totals.item_subtotal))).toBe(100);
  expect(Number(String(totals.shipping_subtotal))).toBe(20);
  expect(
    Number(
      String(
        (totals as typeof totals & { discount_subtotal: unknown })
          .discount_subtotal,
      ),
    ),
  ).toBe(10);
  expect(Number(String(totals.tax_total))).toBe(11);
  expect(Number(String(totals.total))).toBe(121);
});
