import { EventEmitter } from "node:events"
import { authRateLimit, cartOwner, orderOwner, passwordPolicy, paymentOwner, cashfreeProvider } from "../commerce-guards"
import { Modules } from "@medusajs/framework/utils"
function fixture(records:unknown[]=[]){const query={graph:jest.fn(async()=>({data:records}))};const locking={acquire:jest.fn(async()=>{}),release:jest.fn(async()=>true),execute:jest.fn(async(_key:string,fn:()=>Promise<unknown>)=>fn())};const cache=new Map();const caching={get:jest.fn(async({key})=>cache.get(key)),set:jest.fn(async({key,data})=>cache.set(key,data))};const req:any={method:"GET",path:"/store/carts/cart_test",params:{id:"cart_test"},body:{},auth_context:{actor_id:"cus_owner"},scope:{resolve:(key:string)=>key===Modules.LOCKING?locking:key===Modules.CACHING?caching:query},ip:"127.0.0.1"};const res:any=new EventEmitter();res.status=jest.fn(()=>res);res.json=jest.fn(()=>res);res.setHeader=jest.fn();return {req,res,query,locking,next:jest.fn()};}
afterEach(()=>{delete process.env.CHECKOUT_ENABLED;delete process.env.CASHFREE_CLIENT_ID;delete process.env.CASHFREE_CLIENT_SECRET;delete process.env.CASHFREE_ENV;})
function enable(){Object.assign(process.env,{CHECKOUT_ENABLED:"true",CASHFREE_CLIENT_ID:"test",CASHFREE_CLIENT_SECRET:"test",CASHFREE_ENV:"sandbox"})}
it("order authorization queries by both order and signed-in customer",async()=>{const f=fixture();await orderOwner(f.req,f.res,f.next);expect(f.query.graph).toHaveBeenCalledWith(expect.objectContaining({filters:{id:"cart_test",customer_id:"cus_owner"}}));expect(f.res.status).toHaveBeenCalledWith(404);expect(f.next).not.toHaveBeenCalled()})
it.each(["GET","POST","DELETE"])("rejects another customer's cart on %s",async(method)=>{const f=fixture([{id:"cart_test",customer_id:"cus_foreign"}]);f.req.method=method;await cartOwner(f.req,f.res,f.next);expect(f.res.status).toHaveBeenCalledWith(404);expect(f.next).not.toHaveBeenCalled()})
it("prevents direct manual-provider checkout even if Cashfree is also present",async()=>{enable();const f=fixture([{id:"cart_test",customer_id:"cus_owner",payment_collection:{payment_sessions:[{provider_id:cashfreeProvider},{provider_id:"pp_system_default"}]}}]);f.req.method="POST";f.req.path+="/complete";await cartOwner(f.req,f.res,f.next);expect(f.res.status).toHaveBeenCalledWith(400);expect(f.next).not.toHaveBeenCalled()})
it("freezes bag edits after payment starts",async()=>{const f=fixture([{id:"cart_test",customer_id:"cus_owner",payment_collection:{payment_sessions:[{provider_id:cashfreeProvider}]}}]);f.req.method="POST";f.req.path+="/line-items";await cartOwner(f.req,f.res,f.next);expect(f.res.status).toHaveBeenCalledWith(409);expect(f.next).not.toHaveBeenCalled();f.res.emit("finish");expect(f.locking.release).toHaveBeenCalled()})
it("does not permit payment session data injection",async()=>{enable();const f=fixture([{cart_id:"cart_test"}]);f.req.body={provider_id:cashfreeProvider,data:{order_id:"order_forged"}};await paymentOwner(f.req,f.res,f.next);expect(f.res.status).toHaveBeenCalledWith(400);expect(f.next).not.toHaveBeenCalled()})
it("reuses an existing payment session instead of executing native replacement",async()=>{enable();const collection={id:"paycol_test",payment_sessions:[{id:"payses_test",provider_id:cashfreeProvider}]};const f=fixture();f.query.graph.mockResolvedValueOnce({data:[{cart_id:"cart_test"}] as any}).mockResolvedValueOnce({data:[{customer_id:"cus_owner",shipping_address:{id:"a"},shipping_methods:[{id:"s"}],payment_collection:collection}] as any});f.req.body={provider_id:cashfreeProvider};await paymentOwner(f.req,f.res,f.next);expect(f.res.json).toHaveBeenCalledWith({payment_collection:collection});expect(f.next).not.toHaveBeenCalled()})
it("blocks checkout until configured",async()=>{const f=fixture();await paymentOwner(f.req,f.res,f.next);expect(f.res.status).toHaveBeenCalledWith(503)})
it("rate-limits repeated attempts using shared state and opaque keys",async()=>{const f=fixture();f.req.body={email:"private@example.test"};for(let i=0;i<16;i++)await authRateLimit(f.req,f.res,f.next);expect(f.next).toHaveBeenCalledTimes(15);expect(f.res.status).toHaveBeenCalledWith(429);expect(JSON.stringify(f.locking.execute.mock.calls)).not.toContain("private@example.test")})
it("enforces password bounds on the backend",()=>{for(const password of ["short","a".repeat(129)]){const f=fixture();f.req.body={password};passwordPolicy(f.req,f.res,f.next);expect(f.res.status).toHaveBeenCalledWith(400);expect(f.next).not.toHaveBeenCalled()}})
